### ISSUE TITLE
Actual code

### ISSUE THREAD

**Issue by micahlt** [MikeDev101/RaspbianX#3]
Out of curiosity, will there be actual source code posted on GitHub or will it remain a Google Drive link?

**Comment by MikeDev101** [comment]
Probably not. Image files are a decent 28ish GB in size, and even compression only shrinks it down to 2GB. It's too large for GitHub to handle, sadly. (At least, I thinks so, last time I checked.)

**Comment by micahlt** [comment]
Yeah, I imagine that the image files are huge.  How about the source code though?  If details of how to build the source into an image were available, it would also open RaspbianX up to potentially run on other architectures besides the Pi.

**Comment by MikeDev101** [comment]
It's running on top of Raspbian Buster, which by far I'm not aware of any source code that can be compiled into a disk image.

**Comment by micahlt** [comment]
Have you looked at https://github.com/RPi-Distro/pi-gen?  Looks promising.

**Comment by MikeDev101** [comment]
I have, I just haven't the time.
