### ISSUE TITLE
Link down

### ISSUE THREAD

**Issue by MikeDev101** [MikeDev101/RaspbianX#9]
Ok, this isn't an april fools joke (other than build 3.31.2020), but apparently the build 3.21.2020 drive file went missing (Probably Google didn't like having a 16GB img compressed into 2GB zip). I'm going to attempt to host the file once again...

However, I probably can't fix this at the moment due to my NAS being down, as I wait on a part from Amazon so I can back up my files and access the RaspbianX image. (It should be here by 4.3.2020, or Friday).

Besides, I still need to optimize the image file. I'll be recompiling RaspbianX using Raspbian's minimal installation version (no gui, no programs, just vanilla Linux). 

Re-release date TBD...

**Comment by micahlt** [comment]
Yikes... that stinks.  Hope you get that part!  :+1:

**Comment by ConvexPolygon** [comment]
oof moment

**Comment by MikeDev101** [comment]
Okey! The file is now available VIA MediaFire. That should be working. Closing this issue...
